AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BackgroundJobLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: BackgroundJobLambda
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: src/
      Timeout: 30
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - SQSPollerPolicy:
            QueueName: !Select [5, !Split [":", !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:backgroundjobqueue"]]
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:backgroundjobqueue"
            BatchSize: 1  # Number of messages processed at once

Outputs:
  BackgroundJobLambdaArn:
    Description: "ARN of the Lambda Function"
    Value: !GetAtt BackgroundJobLambda.Arn